update lmod and modules for fram
NorESMhub/cime pull request #55
Opened 2023-11-09 08:51 UTC by mvdebolskiy

Changed modules to newer the ones built with newer toolchains. Changed the path to lmod languages. Needed for model to work on the updated Fram.

Test suite:
Test baseline:
Test namelist changes:
Test status: [bit for bit, roundoff, climate changing]

Fixes [CIME Github issue #]

User interface changes?:

Update gh-pages html (Y/N)?:

2023-11-09 09:17 UTC, gold2718 commented
@mvdebolskiy, Can you add a brief note as to how you tested this (e.g., ran an xxx case)?

2023-11-09 09:18 UTC, gold2718 approved these changes
:+1:

2023-11-09 09:22 UTC, mvdebolskiy commented
Tested with 5day run using `N1850` compset and  `f19_tn14` grid. Any other comset I should try?

2023-11-09 09:29 UTC, gold2718 commented on config/cesm/machines/config_machines.xml
> +    <NODENAME_REGEX>.*.?fram\d?.sigma2.no</NODENAME_REGEX>
Thanks, forgot to ask for this.

2023-11-09 09:31 UTC, gold2718 commented
> Tested with 5day run using `N1850` compset and `f19_tn14` grid. Any other comset I should try?

No, I think this type of change either works or not.

2023-11-09 10:41 UTC, mvertens requested changes
@mvdebolskiy - thanks so much for this.
Could we also add the path to CCSM_CPRNC and BASELINE_ROOT for both betzy and fram:
CCSM_CPRNC = /cluster/shared/noresm/tools/cprnc/cprnc
BASELINE_ROOT=/cluster/shared/noresm/noresm_baselines

2023-11-09 12:06 UTC, mvdebolskiy commented
Done.

2023-11-09 12:10 UTC, mvertens commented
@mvdebolskiy - thanks so much! this is super helpful.

2023-11-09 12:11 UTC, mvertens approved these changes

2023-11-09 17:03 UTC, mvdebolskiy commented
Tested with `--res f19_tn14--compset N1850frc2 --pecount 128 --queue devel` on betzy. Works. Also RESUBMIT does not fail. Only weird thing is st._archive jobs take around 7 minutes. (also, had to do `NTASKS_OCN=123` since 128 does not work). Also, now you can check out small number of nodes on `preproc` queue for a really small job.

2023-11-09 18:49 UTC, merged

2023-11-09 18:50 UTC, mvertens commented
@mvdebolskiy - thanks for this and for the testing. This will be super helpful in the upcoming release.

2023-11-10 09:45 UTC, mvdebolskiy commented
Should also fix #49 for betzy. Is #49 needs to fix it on fram also?

2023-11-10 15:02 UTC, gold2718 commented
> Should also fix #49 for betzy. Is #49 needs to fix it on fram also?

Is the queue structure the same? The request I received was for Betzy since support for the devel queue had been removed for the NorESM2 release due to some problem which I understand has been resolved. Does Fram have any useful queues that are not listed in its config entry?

2023-11-13 12:00 UTC, mvdebolskiy commented
@gold2718 the only reson we have to use `devel` and `preproc` queues on betzy is that normal queue demands the checkout of at least 4 nodes. Fran does not have this issue. I can add more queues to fram but I doubt anyone would use them to run release code.